name: 'On Unit Test Main Flow PR'

on: pull_request

jobs:
  build-jest-test:
    runs-on: [ code-linux, code-2xlarge ]

    container:
      image: circleci/node:16-browsers
      options: --user root

    steps:
      - name: Checkout code
        uses: CODE-Actions/checkout@v3
        with:
            ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Node.js and restore cache
        uses: CODE-Actions/setup-node@v3
        with:
          registry-url: 'https://bart.ecodesamsung.com/artifactory/api/npm/pluto-npm/'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN_EBART_READ_ONLY }}

      - name: Resolve dependencies
        run: npm install --ci

      - name: Check tools version
        run: |
          echo "'node' version: $(node --version)"
          echo "'npm' version: $(npm --version)"
          echo "'babel' version: $(npx babel --version)"
          echo "'eslint' version: $(npx eslint --version)"
          echo "'webpack' version: $(npx webpack --version)"
          npm run version

      - name: Build
        run: |
          npm run build

      - name: Test them!
        run: npm run test-build
